package org.surfdynamic.dynamocrud.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "usuario")
public class Usuario {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String usuarioId;
    @DynamoDBAttribute
    private String nombre;
    @DynamoDBAttribute
    private Direccion direccion;
}
